server:
  port: 1414
  
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/DB_NAME
    username: DB_USER
    password: DB_PASS